services:
  - type: web
    name: hospital-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn hospital_site.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: hospital_site.settings
